version: "3.9"

services:
 web:
    # properties
    image: nginx:latest
    container_name: rms_nginx

    # settings
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

    # commands
    command: /bin/bash -c \
      "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
      nginx -g 'daemon off;'"

    # dependencies
    env_file:
      - ${PWD}/.env
    depends_on:
      - app

    # attachments
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    networks:
      - rms_net
  
networks:
  rms_net:
    driver: bridge