name: Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
        
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Tests
        run: |
          make build-tests
          make tests
